# JRuby
:real:
  :adapter: jdbcmysql
  :database: kml_shapes_real
  :hostname: localhost
  :username: root
  :password: w00w00
  :port: 3306

:test:
  :adapter: jdbcmysql
  :database: kml_shapes_test
  :hostname: localhost
  :username: root
  :password: w00w00
  :port: 3306


